Added estimated time
PlaceNL/Chief pull request #17
Opened 2023-07-22 12:46 UTC by WiserTixx

2023-07-22 12:56 UTC, NoahvdAa requested changes

2023-07-22 12:56 UTC, NoahvdAa commented on web/index.html
> +                        document.querySelector('#time-minutes-left').innerText = Math.floor(timeLeft % 60);
Completion stats are optional (reddit integration can be turned off), see the if block below. The ETA should be hidden if we don't know completion.

2023-07-22 15:05 UTC, NoahvdAa requested changes
No clue how this happens, but for me this change causes the tab CPU usage to rise to 100% for a few seconds before the tab completely crashes.

2023-07-22 22:57 UTC, WiserTixx commented
> No clue how this happens, but for me this change causes the tab CPU usage to rise to 100% for a few seconds before the tab completely crashes.
> 
> EDIT: It's because of odometer. Some value ends up becoming Infinity (due to my local instance having 0 place cabale clients / the wrong pixel count not loading in yet), so odometer dies trying to calculate how fast it should move.

I to replicate the issue but I was unable to. I've still added checks tho in an attempt to resolve the issue.

2023-07-23 10:44 UTC, NoahvdAa approved these changes

2023-07-23 10:44 UTC, merged